### ISSUE TITLE
oc load failed unsupported 

### ISSUE THREAD

**Issue by karimrj49** [Hasodikis/ThinkPad-t460-Hackintosh-OpenCore#2]
when boot to efie it's say's oc load failed unsupported  any help ?

**Comment by karimrj49** [comment]
any Help ?

**Comment by Hasodikis** [comment]
No clue at all

**Comment by nguyenminhhao9988** [comment]
same issue 
"grabbed zero system-id for SB, this is not allowed. Halting on critical error."
I try to boot on Intel Wifi, I replaced kexts for intel already
